### ISSUE TITLE
How to specify pytorch device?

### ISSUE THREAD

**Issue by ivoras** [1-800-BAD-CODE/punctuators#9]
Thanks for this wrapper! But, how can we specify the (CUDA) device to be used for inference?

**Comment by 1-800-BAD-CODE** [comment]
If you update to the latest version from pypi (0.0.6), the punctuation models should use CUDA when available, or fall back on CPU if not. 

I don't have a local GPU so I didn't test the CUDA functionality.

```bash
$ pip install punctuators --upgrade
```
